# Generated by Django 3.2.3 on 2021-08-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_list',
            name='Carb',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='search_list',
            name='Fat',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='search_list',
            name='Fiber',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='search_list',
            name='Protein',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='search_list',
            name='list_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
