# Generated by Django 3.2.3 on 2021-08-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cut', '0002_auto_20210809_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_list',
            name='cal',
            field=models.CharField(default='', max_length=50),
        ),
    ]
