# Generated by Django 3.2.3 on 2021-08-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cut', '0003_search_list_cal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_list',
            name='Carb',
        ),
        migrations.RemoveField(
            model_name='search_list',
            name='Fat',
        ),
        migrations.RemoveField(
            model_name='search_list',
            name='Fiber',
        ),
        migrations.RemoveField(
            model_name='search_list',
            name='Protein',
        ),
        migrations.RemoveField(
            model_name='search_list',
            name='cal',
        ),
        migrations.AlterField(
            model_name='search_list',
            name='list_name',
            field=models.CharField(max_length=50),
        ),
    ]
