# Generated by Django 3.2.3 on 2021-08-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cut', '0004_auto_20210815_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_list',
            name='Cal',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='search_list',
            name='Carb',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='search_list',
            name='Fat',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='search_list',
            name='Fiber',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='search_list',
            name='Protein',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='search_list',
            name='list_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
